function GraficeTranzistor(A,f,RG1,RG2,VDD,RD,RL,VP,b,Id,VA,N)
if A==0||N<=0||f<=0||VDD<=0
    j=errordlg('Valoarea este incorecta!','Error');
end


VD=(VDD-(Id*RD));
VGS=(sqrt(Id/b)+VP);
gm=(2*b*(VGS-VP));
rds=VA/Id;
R1=((rds*RD)/(rds+RD));
Rtotal=((R1*RL)/(R1+RL));
Av=((-gm)*Rtotal);
VG=((RG2/(RG1+RG2))*VDD);

 Fig=figure('Name','Grafice',...
     'Units','normalized',...
    'Position',[0.05 0.1 0.9 0.7],...
    'NumberTitle','off', 'Color','#E4D1FF');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.01 0.8 0.05 0.05],...
 'backgroundcolor','#E4D1FF',...
 'foregroundcolor','black',...
 'String',' A [V]');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.01 0.75 0.05 0.05],...
 'foregroundcolor','black',...
 'String',A,...
 'Callback','A=str2num(get(gco,''string''));close;GraficeTranzistor(A,f,RG1,RG2,VDD,RD,RL,VP,b,Id,VA,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.01 0.65 0.05 0.05],...
 'backgroundcolor','#E4D1FF',...
 'foregroundcolor','black',...
 'String',' f [Hz]');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.01 0.60 0.05 0.05],...
 'foregroundcolor','black',...
 'String',f,...
 'Callback','f=str2num(get(gco,''string'')); close;GraficeTranzistor(A,f,RG1,RG2,VDD,RD,RL,VP,b,Id,VA,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.01 0.5 0.05 0.05],...
 'backgroundcolor','#E4D1FF',...
 'foregroundcolor','black',...
 'String',' VDD [V]');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.01 0.45 0.05 0.05],...
 'foregroundcolor','black',...
 'String',VDD,...
 'Callback','VDD=str2num(get(gco,''string'')),close;GraficeTranzistor(A,f,RG1,RG2,VDD,RD,RL,VP,b,Id,VA,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.01 0.35 0.05 0.05],...
 'backgroundcolor','#E4D1FF',...
 'foregroundcolor','black',...
 'String','N');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.01 0.3 0.05 0.05],...
 'foregroundcolor','black',...
 'String',N,...
 'Callback','N=str2num(get(gco,''string''));close;GraficeTranzistor(A,f,RG1,RG2,VDD,RD,RL,VP,b,Id,VA,N)');


 uicontrol('Style', 'Text',...
    'Units', 'normalized',...
    'Position',[0.1 0.95 0.4 0.03],...
    'FontName','Times New Roman',...
    'FontSize', 12,...
    'FontWeight','bold',...
    'BackgroundColor','#E4D1FF',...
    'String', ' vi ');

 uicontrol('Style', 'Text',...
    'Units', 'normalized',...
    'Position',[0.55 0.95 0.4 0.03],...
    'FontName','Times New Roman',...
    'FontSize', 12,...
    'FontWeight','bold',...
    'BackgroundColor','#E4D1FF',...
    'String', ' vG=vi+VG ');

  uicontrol('Style', 'Text',...
    'Units', 'normalized',...
    'Position',[0.1 0.47 0.4 0.03],...
    'FontName','Times New Roman',...
    'FontSize', 12,...
    'FontWeight','bold',...
    'BackgroundColor','#E4D1FF',...
    'String', ' vo=Av*vi ');
   uicontrol('Style', 'Text',...
    'Units', 'normalized',...
    'Position',[0.55 0.47 0.4 0.03],...
    'FontName','Times New Roman',...
    'FontSize', 12,...
    'FontWeight','bold',...
    'BackgroundColor','#E4D1FF',...
    'String', ' vO(t)=vD+vo ');

 %vi
subplot(221);
T=1/f
t=(0:T/100:T*N);
vi=A*sin(2*pi*f*t);

 for i=1:length(t)
           if vi(i)>VDD
               vi(i)=VDD
           elseif vi(i)<-VDD
               vi(i)=-VDD
               
           end
           end
plot(t,vi,'Color','m');
grid on; 


%vG
subplot(222);
vG=vi+VG;
plot(t,vG,'Color','r');
grid on;

%vo
subplot(223);
vo=Av*vi;
plot(t,vo,'Color','c');
grid on;

%vO
subplot(224);
vO=VD+vo;
plot(t,vO,'Color','g');
grid on;

uicontrol('Style','pushbutton',...
    'Units', 'normalized',...
    'Position', [0.4 0.01 0.2 0.05],...
    'String', 'INAPOI',...
    'Callback', 'close;Proiect()');