function PunctulStaticFunctionare(VDD,RD,Id)
figure('Name','Punctul static de functionare',...
    'Units','normalized',...
    'Position',[0.1 0.1 0.75 0.75],...
    'NumberTitle','off', 'Color','#E4D1FF');



uicontrol('Style', 'Text',...
    'Units', 'normalized',...
    'Position',[0.02 0.92 0.4 0.05],...
    'FontSize', 12,...
    'FontName','Times New Roman',...
     'FontWeight','bold',...
    'BackgroundColor','#E4D1FF',...
    'String', 'Punctul static de funcționare');


uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',10,...
 'FontName','Times New Roman',...
 'Position',[0.15 0.88 0.15 0.05],...
 'backgroundcolor','#E4D1FF',...
 'FontWeight','bold',...
 'foregroundcolor','black',...
 'String','Q ( Id ; VDS )');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
 'FontName','Times New Roman',...
 'Position',[0.05 0.7 0.1 0.05],...
 'backgroundcolor','#E4D1FF',...
 'foregroundcolor','black',...
 'String','ID [mA]  =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.14 0.71 0.1 0.05],...
 'foregroundcolor','black',...
 'String',Id,...
 'Callback','Id=str2num(get(gco,''string'')), close;PunctulStaticFunctionare(Id,VDD,RD)');


VDS=(VDD-(RD*Id));
I=[0 Id 100];
V=[0 VDS VDD];
subplot('Position',[0.43 0.4 0.5 0.5]);
plot(V,I,'-or','Color','m');
xlabel('VDS [V]');
ylabel('ID [A]');
hold on;
grid on;

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
 'FontName','Times New Roman',...
 'Position',[0.05 0.63 0.1 0.05],...
 'backgroundcolor','#E4D1FF',...
 'foregroundcolor','black',...
 'String','VDS [V]  =');


uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.14 0.64 0.1 0.05],...
 'foregroundcolor','black',...
 'String',VDS,...
 'Callback','VDS=str2num(get(gco,''string'')),close;PunctulStaticFunctionare(VDD,RD,Id)');



uicontrol('Style','pushbutton',...
    'Units', 'normalized',...
    'Position', [0.4 0.05 0.2 0.05],...
    'String', 'INAPOI',...
    'Callback', 'close;Proiect()');
