function SchemaDeSemnalMic()
 Fig=figure('Name','Schema de semnal mic',...
     'Units','normalized',...
    'Position',[0.05 0.1 0.9 0.7],...
    'NumberTitle','off', 'Color','#E4D1FF');
    

[figura]=imread('schemaSemnalMic.png');
image(figura);
axis off;
title('Schema de semnal mic:','FontName',"Times New Roman", 'FontSize',12);

uicontrol('Style','pushbutton',...
    'Units', 'normalized',...
    'Position', [0.4 0.05 0.2 0.05],...
    'String', 'INAPOI',...
    'Callback', 'close;Proiect()');