function tranzistor (A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)
%afisam eroare daca parametrii primesc valoare mai mica sau egala cu 0
%VA este un parametru cuprins intre 15 si 150 cand vine vorba de TMOS
if A==0||RG1<=0||RG2<=0||RD<=0||RL<=0||f<=0||VDD<=0||VP<=0||VA>=150||VA<=15
    z=errordlg('Valoarea este incorecta!','Error');
end
Fig=figure('Name','Amplificator fundamental cu TECMOS',...
    'Units','normalized',...
    'Position',[0.1 0.1 0.75 0.75],...
    'NumberTitle','off', 'Color','#E4D1FF');

uicontrol('Style', 'Text',...
    'Units', 'normalized',...
    'Position',[0.1 0.92 0.4 0.05],...
    'FontSize', 13,...
     'FontName','Times New Roman',...
     'FontWeight','bold',...
    'BackgroundColor','#E4D1FF',...
    'String', 'Conexiunea sursă comună la TECMOS');

VGS=(sqrt(Id/b)+VP);
gm=(2*b*(VGS-VP));
rds=VA/Id;

Ri=((RG1*RG2)/(RG1+RG2));

Ro=((RD*rds)/(RD+rds));

R1=((rds*RD)/(rds+RD));
Rtotal=((R1*RL)/(R1+RL));
Av=((-gm)*Rtotal);

ButtonGroup2=uibuttongroup('Visible','on',...
 'BackgroundColor','#EFE5FD',...
'ForegroundColor','black',...
 'Title',' Semnalul de intrare:  ',...
 'FontSize',12,...
  'FontName','Times New Roman',...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.3 0.7 0.2 0.2]);

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.31 0.79 0.05 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String',' A [V] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.38 0.8 0.1 0.05],...
 'foregroundcolor','black',...
 'String',A,...
 'Callback','A=str2num(get(gco,''string'')),close;tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.31 0.72 0.05 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String',' f [Hz] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.38 0.73 0.1 0.05],...
 'foregroundcolor','black',...
 'String',f,...
 'Callback','f=str2num(get(gco,''string'')), close; tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');


subplot('Position', [0.55 0.15 0.35 0.3]);
title('Semnalul de intrare:','FontSize',12,'FontName','Times New Roman')
T=1/f
t=(0:T/100:2*T);
vi=A.*sin(2.*pi.*f.*t);

 for i=1:length(t)
           if vi(i)>VDD
               vi(i)=VDD
           elseif vi(i)<-VDD
               vi(i)=-VDD
           end
 end
plot(t,vi,'Color','m');
grid on;
 
        

uicontrol('Style', 'Text',...
    'Units', 'normalized',...
    'Position',[0.53 0.47 0.4 0.03],...
    'FontName','Times New Roman',...
    'FontSize', 12,...
    'FontWeight','bold',...
    'BackgroundColor','#E4D1FF',...
    'String', 'Semnalul de intrare (Vin): ');

uicontrol('Style', 'Text',...
    'Units', 'normalized',...
    'Position',[0.52 0.89 0.4 0.03],...
    'FontName','Times New Roman',...
    'FontSize', 12,...
    'FontWeight','bold',...
    'BackgroundColor','#E4D1FF',...
    'String', 'Circuitul propus: ');

 subplot('position',[0.55 0.58 0.35 0.3]);
im=imread('Figura1.png');
image(im);
axis off;

ButtonGroup1=uibuttongroup('Visible','on',...
 'BackgroundColor','#EFE5FD',...
'ForegroundColor','black',...
 'Title','Datele circuitului:',...
 'FontSize',12,...
  'FontName','Times New Roman',...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.03 0.2 0.25 0.7]);

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.05 0.78 0.1 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','RG1 [kohm] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.15 0.79 0.1 0.05],...
 'foregroundcolor','black',...
 'String',RG1,...
 'Callback','RG1=str2num(get(gco,''string'')),close;tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.05 0.71 0.1 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','RG2 [kohm] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.15 0.72 0.1 0.05],...
 'foregroundcolor','black',...
 'String',RG2,...
 'Callback','RG2=str2num(get(gco,''string'')),close;tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.05 0.64 0.1 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','RD [kohm] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.15 0.65 0.1 0.05],...
 'foregroundcolor','black',...
 'String',RD,...
 'Callback','RD=str2num(get(gco,''string'')),close;tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.05 0.57 0.1 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','RL [kohm] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.15 0.58 0.1 0.05],...
 'foregroundcolor','black',...
 'String',RL,...
 'Callback','RL=str2num(get(gco,''string'')),close;tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
 'FontName','Times New Roman',...
 'Position',[0.05 0.5 0.1 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','VDD [V] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.15 0.51 0.1 0.05],...
 'foregroundcolor','black',...
 'String',VDD,...
 'Callback','VDD=str2num(get(gco,''string'')),close;tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
 'FontName','Times New Roman',...
 'Position',[0.05 0.43 0.1 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','VP [V] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.15 0.44 0.1 0.05],...
 'foregroundcolor','black',...
 'String',VP,...
 'Callback','VP=str2num(get(gco,''string'')),close;tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
 'FontName','Times New Roman',...
 'Position',[0.05 0.37 0.1 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','Id [mA] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.15 0.38 0.1 0.05],...
 'foregroundcolor','black',...
 'String',Id,...
 'Callback','Id=str2num(get(gco,''string'')),close;tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
 'FontName','Times New Roman',...
 'Position',[0.05 0.3 0.1 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','b [mA/V*V] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.15 0.31 0.1 0.05],...
 'foregroundcolor','black',...
 'String',b,...
 'Callback','b=str2num(get(gco,''string'')),close;tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',9,...
 'FontName','Times New Roman',...
 'Position',[0.05 0.23 0.1 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','VA [V] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.15 0.24 0.1 0.05],...
 'foregroundcolor','black',...
 'String',VA,...
 'Callback','VA=str2num(get(gco,''string'')),close;tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');

ButtonGroup3=uibuttongroup('Visible','on',...
 'BackgroundColor','#EFE5FD',...
'ForegroundColor','black',...
 'Title',' Valorile parametrilor:  ',...
 'FontSize',12,...
  'FontName','Times New Roman',...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.3 0.2 0.2 0.47]);

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',10,...
  'FontName','Times New Roman',...
 'Position',[0.32 0.54 0.06 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','gm [mS] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',9,...
  'FontName','Times New Roman',...
 'Position',[0.39 0.55 0.1 0.05],...
 'foregroundcolor','black',...
 'String',gm,...
 'Callback','gm=str2num(get(gco,''string''))');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',10,...
  'FontName','Times New Roman',...
 'Position',[0.32 0.46 0.06 0.06],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','rds [kohm] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',10,...
  'FontName','Times New Roman',...
 'Position',[0.39 0.47 0.1 0.05],...
 'foregroundcolor','black',...
 'String',rds,...
 'Callback','rds=str2num(get(gco,''string''))');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',10,...
  'FontName','Times New Roman',...
 'Position',[0.32 0.38 0.06 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','Av =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',10,...
  'FontName','Times New Roman',...
 'Position',[0.39 0.39 0.1 0.05],...
 'foregroundcolor','black',...
 'String',Av,...
 'Callback','Av=str2num(get(gco,''string''))');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',10,...
  'FontName','Times New Roman',...
 'Position',[0.31 0.305 0.08 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','Ri [kohm] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',10,...
  'FontName','Times New Roman',...
 'Position',[0.39 0.315 0.1 0.05],...
 'foregroundcolor','black',...
 'String',Ri,...
 'Callback','Ri=str2num(get(gco,''string''))');

uicontrol('Style','text',...
 'Units','normalized',...
 'FontSize',10,...
  'FontName','Times New Roman',...
 'Position',[0.31 0.22 0.08 0.05],...
 'backgroundcolor','#EFE5FD',...
 'foregroundcolor','black',...
 'String','Ro [kohm] =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'FontSize',10,...
  'FontName','Times New Roman',...
 'Position',[0.39 0.23 0.1 0.05],...
 'foregroundcolor','black',...
 'String',Ro,...
 'Callback','Ro=str2num(get(gco,''string'')),close;tranzistor(A,f,RG1,RG2,RD,RL,VP,b,Id,VA,VDD,N)');

uicontrol('Style','pushbutton',...
    'Units', 'normalized',...
    'Position', [0.05 0.12 0.2 0.05],...
     'FontName','Times New Roman',...
     'FontSize', 10,...
    'String', 'Afișare schema de semnal mic',...
    'Callback', 'close;SchemaDeSemnalMic()');

uicontrol('Style','pushbutton',...
    'Units', 'normalized',...
    'Position', [0.05 0.05 0.2 0.05],...
    'String', 'Punct static de funcționare',...
     'FontName','Times New Roman',...
     'FontSize', 10,...
    'Callback', 'close;PunctulStaticFunctionare(VDD,RD,Id)');

uicontrol('Style', 'checkbox',...
    'Units', 'normalized',...
    'Position', [0.3 0.12 0.2 0.05],...
    'String', 'Afișare grafice',...
    'FontName','Times New Roman',...
    'FontSize',10,...
    'BackgroundColor','#E4D1FF',...)
    'Callback','close;GraficeTranzistor(A,f,RG1,RG2,VDD,RD,RL,VP,b,Id,VA,N)');
uicontrol('Style', 'checkbox',...
    'Units', 'normalized',...
    'Position', [0.3 0.05 0.2 0.05],...
    'String', 'Revenire la starea inițială',...
    'FontName','Times New Roman',...
    'FontSize',10,...
    'BackgroundColor','#E4D1FF',...)
    'Callback','close;Proiect()');


m=uimenu('Label','Documentație proiect','Callback','open(''Documentatie.pdf'')'); 
  


